In [2]:
 pip install --upgrade pandas

Requirement already satisfied: pandas in c:\users\kpran\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kpran\anaconda3\lib\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kpran\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kpran\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kpran\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\kpran\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import numpy as np
import pandas as pd
print(pd.__version__)

2.2.3

In [ ]:
#Pandas
#Series --> IS A 1D labelled data

#Dataframe --> represent the data in tabular form(rows and columns)

In [6]:
arr = pd.array([10,20,30,40])
print(type(arr))

<class 'pandas.core.arrays.integer.IntegerArray'>

In [7]:
s = pd.Series(arr)
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
dtype: Int64

In [10]:
s = pd.Series([10,20,30],index=['val1','val2','val3'])
print(s)
print(s['val1'])
print(s.iloc[0])

val1    10
val2    20
val3    30
dtype: int64
10
10

In [18]:
s = pd.Series([10,20,30,40,50,60],index=['val1','val2','val3','val4','val5','val6'])
print(s)
print(s[0:4])
print(s['val1':'val4'])

print('using for loop')
for i in s:
    print(i)

val1    10
val2    20
val3    30
val4    40
val5    50
val6    60
dtype: int64
val1    10
val2    20
val3    30
val4    40
dtype: int64
val1    10
val2    20
val3    30
val4    40
dtype: int64
using for loop
10
20
30
40
50
60

In [26]:
s = pd.Series([10,20,30,40,50,60],index=['val1','val2','val3','val4','val5','val6'])
print(s)
print(s.get('val5'))  #for printing value of that index
print(s.values)   #all the values
print(s.shape)    # whether the array is 1d or 2d
print(s.index)    #print all the index 
print(s.dtype)

#perform numericla computation
print('\nperform numerical computation')
print(s*2)

val1    10
val2    20
val3    30
val4    40
val5    50
val6    60
dtype: int64
50
[10 20 30 40 50 60]
(6,)
Index(['val1', 'val2', 'val3', 'val4', 'val5', 'val6'], dtype='object')
int64

perform numerical computation
val1     20
val2     40
val3     60
val4     80
val5    100
val6    120
dtype: int64

In [28]:
#DATAFRAME --> data in a tabular format

emp_info={'Name':['John','Alex','Smith'],'Dept':['IT','Sales','Finance'],'Salary':[35000,20000,40000]}
print(emp_info)

{'Name': ['John', 'Alex', 'Smith'], 'Dept': ['IT', 'Sales', 'Finance'], 'Salary': [35000, 20000, 40000]}

In [29]:
data = pd.DataFrame(emp_info)
print(type(data))
print(data)

<class 'pandas.core.frame.DataFrame'>
    Name     Dept  Salary
0   John       IT   35000
1   Alex    Sales   20000
2  Smith  Finance   40000

In [30]:
data

    Name     Dept  Salary
0   John       IT   35000
1   Alex    Sales   20000
2  Smith  Finance   40000

In [5]:
emp_info={'Name':['John','Alex','Smith'],'Dept':['IT','Sales','Finance'],'Salary':[35000,20000,40000]}
data = pd.DataFrame(emp_info,index=['emp1','emp2','emp3'])
data

       Name     Dept  Salary
emp1   John       IT   35000
emp2   Alex    Sales   20000
emp3  Smith  Finance   40000

In [1]:
#DataFrame Methods
#head,tail,shape,columns,describe,info,nunique

In [9]:
print(data.head(5)) #returns starting rows

       Name     Dept  Salary
emp1   John       IT   35000
emp2   Alex    Sales   20000
emp3  Smith  Finance   40000

In [10]:
print(data.tail(1))  #returns ending rows

       Name     Dept  Salary
emp3  Smith  Finance   40000

In [12]:
print(data.info())  #returns info abt our data

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, emp1 to emp3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Dept    3 non-null      object
 2   Salary  3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes
None

In [16]:
data.describe()  #procide percentile,min,max and extra info

             Salary
count      3.000000
mean   31666.666667
std    10408.329997
min    20000.000000
25%    27500.000000
50%    35000.000000
75%    37500.000000
max    40000.000000

In [33]:
print(data.shape)  #returns rows and columns

(3, 3)

In [36]:
data.columns  #returns name of the columns

Index(['Name', 'Dept', 'Salary'], dtype='object')

In [38]:
data.Dept.values

array(['IT', 'Sales', 'Finance'], dtype=object)

In [39]:
data[['Dept','Salary']]

         Dept  Salary
emp1       IT   35000
emp2    Sales   20000
emp3  Finance   40000

In [40]:
#Locate row
data.loc['emp1']

Name       John
Dept         IT
Salary    35000
Name: emp1, dtype: object

In [43]:
data.loc[['emp2','emp3']]

       Name     Dept  Salary
emp2   Alex    Sales   20000
emp3  Smith  Finance   40000

In [46]:
#data_range('yyyymmdd',periods=10)
dates = pd.date_range('20250204',periods=10)
dates

DatetimeIndex(['2025-02-04', '2025-02-05', '2025-02-06', '2025-02-07',
               '2025-02-08', '2025-02-09', '2025-02-10', '2025-02-11',
               '2025-02-12', '2025-02-13'],
              dtype='datetime64[ns]', freq='D')

In [50]:
df = pd.DataFrame(np.random.rand(10,4),index=dates,columns=list ('ABCD'))
df

                   A         B         C         D
2025-02-04  0.315904  0.078897  0.858204  0.720473
2025-02-05  0.712823  0.220665  0.388793  0.384249
2025-02-06  0.786911  0.989074  0.938387  0.854172
2025-02-07  0.036736  0.056337  0.410288  0.596228
2025-02-08  0.927455  0.299929  0.028323  0.039447
2025-02-09  0.604806  0.342430  0.705542  0.131226
2025-02-10  0.127796  0.826538  0.746810  0.605545
2025-02-11  0.878381  0.295710  0.247913  0.241775
2025-02-12  0.717998  0.241299  0.295752  0.437884
2025-02-13  0.914100  0.387012  0.649276  0.078447

In [51]:
emp_info = {'Id':[101,102,103,104,105,106],'Name':['John','Smith','Nurul','Tom','Harry','Smith'],'Salary':[1000,2000,3000,1200,4000,2800],'Dept':['Finance','Sales','HR','IT','Marketing','Sales']}
data = pd.DataFrame(emp_info)
data

    Id   Name  Salary       Dept
0  101   John    1000    Finance
1  102  Smith    2000      Sales
2  103  Nurul    3000         HR
3  104    Tom    1200         IT
4  105  Harry    4000  Marketing
5  106  Smith    2800      Sales

In [55]:
data[data['Salary']>1500]

    Id   Name  Salary       Dept
1  102  Smith    2000      Sales
2  103  Nurul    3000         HR
4  105  Harry    4000  Marketing
5  106  Smith    2800      Sales

In [59]:
data[(data['Salary']>1500) & (data['Dept']=='Sales')]

    Id   Name  Salary   Dept
1  102  Smith    2000  Sales
5  106  Smith    2800  Sales

In [60]:
#Pandas 
#reading an excel file,csv file
#reading tab-delimited file
#reading a JSON file
#uploading local files in jupyter/google colab

In [65]:
#reading an excel file
#read_excel()
data = pd.read_excel('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
data

,id,first_name,last_name,email,gender,ip_address
0,1,Merle,Draisey,mdraisey0@squarespace.com,Bigender,20.70.199.51
1,2,Casey,Sheach,csheach1@deviantart.com,Male,226.126.229.167
2,3,Darya,Leivers,dleivers2@imgur.com,Female,247.209.88.235
3,4,Fancie,Casebourne,fcasebourne3@g.co,Female,172.34.162.239
4,5,Jenilee,Vsanelli,jvsanelli4@fc2.com,Female,200.104.246.2
...,...,...,...,...,...,...
995,996,Lutero,Yurov,lyurovrn@un.org,Male,95.146.16.187
996,997,Verla,Peery,vpeeryro@com.com,Female,172.90.253.234
997,998,Fran,Langran,flangranrp@ft.com,Male,123.179.99.154
998,999,Gabbi,Cummins,gcumminsrq@jugem.jp,Female,190.13.174.159
999,1000,Gloriane,Marc,gmarcrr@businessweek.com,Female,139.87.192.32

In [63]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\kpran\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\kpran\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [66]:
excelfile = pd.ExcelFile('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
excelfile.sheet_names

['data', 'Sheet2']

In [68]:
data = pd.read_excel(excelfile, 'Sheet2')
data

   first_name    last_name                                 email
0       Merle      Draisey             mdraisey0@squarespace.com
1       Casey       Sheach               csheach1@deviantart.com
2       Darya      Leivers                   dleivers2@imgur.com
3      Fancie   Casebourne                     fcasebourne3@g.co
4     Jenilee     Vsanelli                    jvsanelli4@fc2.com
5    Charmian    Drinkhall       cdrinkhall5@theglobeandmail.com
6     Janessa       Kivell                 jkivell6@linkedin.com
7       Mirna       Heinsh                  mheinsh7@spotify.com
8       Darby          Lax                   dlax8@people.com.cn
9       Meryl        Riehm                 mriehm9@princeton.edu
10       Anne        Brody                    abrodya@sphinn.com
11       Puff    Langsbury             plangsburyb@canalblog.com
12       Tina      Gregoli                  tgregolic@sfgate.com
13     Barbie       Dahlen                     bdahlend@narod.ru
14     Andeee  Dobrovolski  adobrovolskie@networkadvertising.org
15    Ainsley       Friman                      afrimanf@irs.gov
16        Bil     Shalcros                 bshalcrosg@dion.ne.jp
17    Raimund     Outridge                   routridgeh@lulu.com
18     Whitby     Millward                    wmillwardi@ask.com
19        Rob      Boarder                       rboarderj@51.la
20      Nicky     Curthoys                    ncurthoysk@pbs.org

In [ ]:
#EXAMPLE - Kaggle Dataset

In [18]:
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [19]:
#selecting data

df['country']

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: object

In [22]:
df[["country","aqi"]]

      country  aqi
0          US  108
1          US   90
2          US   84
3          US  158
4          US   97
...       ...  ...
17995      CH  103
17996      CH  105
17997      CH  122
17998      CH   95
17999      CH   88

[18000 rows x 2 columns]

In [24]:
#loc-locaation of any particular row through their index and it is label based
#we can use column name directly
#starting-ending(exclusive)
df.loc[3:6]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
5,2025-11-04 23:25:17.554219,US,New York,40.713,-74.006,31.242,92.779,30.633,8.030,43.725,0.347,92,15.159,42.505,1.199
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542

In [25]:
#iloc-location of particular row through index and it is integer(numeric) based
#we have to use column position to get values
#starting-(ending-1)(inclusive)
df.iloc[2:5]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [30]:
#Filtering of Data

df[(df["aqi"]>100) & (df["temperature"] > 30)]

df[df["aqi"] >100 ][["city","aqi"]]

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]

In [ ]:
#CLEANING DATA
#Handling Missing values
#isnull(),dropna(),isnull().sum(),fillna()

In [ ]:
#Duplicated Values
#duplicated(),drop_duplicates()